name: Deploy Lambda Code

on:
  push:
    branches: [main]
    paths:
    - 'src/**'
  workflow_dispatch:

jobs:
  deploy-lambda-code:
    runs-on: [self-hosted]
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Run Lambda package & deploy script
        env:
          AWS_REGION: ap-southeast-2
          AWS_ROLE_ARN: arn:aws:iam::775851132745:role/testGithubAction
          LAMBDA_JSON_SECRET: ${{ secrets.LAMBDA_JSON_SECRET }}
        run: |
          echo "Packaging and deploying Lambda..."
          # Example: zip lambda code, upload to S3, update function
          
